version: '3.7'

services:
  scrapper:
    build: .
    container_name: scrapper
    command: npm run dev
    working_dir: /app
    expose:
      - 3000
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
